# Constructs a motion plan for the end effector given the an initial and a target pose for a given mesh
#
# The poses are assumed to be defined in the same reference frame over which the mesh is defined

string mesh_path                # path to the mesh where the plan shall live
string mesh_link_name           # name of the link associated to the mesh
geometry_msgs/PoseStamped y0    # initial pose
geometry_msgs/PoseStamped g     # target pose
float64 offset                  # offset, in meters, of the trajectory from the mesh
float64 max_vel                 # maximum velocity of the end-effector in m/s
---
bool success                            # wether the planning was successfull or not
magician_msgs/CartesianMotionPlan plan  # resulting planned motion
