# Executes an end effector point-to-point motion from an initial to a target pose on a given mesh.
# Optionally, it can pre-pend a motion plan to reach such initial configuration.

string mesh                     # mesh where the motion shall be planned on. See the :ref:`mesh-handling` guide in the documentation for more references
geometry_msgs/PoseStamped y0    # initial pose
geometry_msgs/PoseStamped g     # target pose
float64 offset                  # offset, in meters, of the trajectory from the mesh
float64 max_vel 0.25            # maximum velocity in m/s
bool plan_y0_motion false       # wether a motion to reach y0 shall be executed or not
float64 approach_vel 0.15      
magician_msgs/ControlMode control_mode # which type of control to use to perform the motion
---
bool success
