# Service that provides an estimate of the time to perform point-to-point motion to different poses.

# Let "n" be the number of poses, this service builds a "n x n" time-transition matrix containing, where each entry "t[i, j]" contains the time (in seconds) required to move from pose "i" to pose "j".

geometry_msgs/Pose[] poses
string frame_id             # reference frame in which poses are defined;

---
std_msgs/Float64MultiArray time_transition_matrix
